[project]
name = "decloud"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django (>=5.1.5,<6.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "drf-yasg (>=1.21.8,<2.0.0)",
    "djangorestframework (>=3.15.2,<4.0.0)",
    "boto3 (>=1.37.9,<2.0.0)",
<<<<<<< HEAD
    "psycopg (>=3.2.6,<4.0.0)"
=======
    "djangorestframework-simplejwt (>=5.5.0,<6.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "django-cors-headers (>=4.7.0,<5.0.0)",
>>>>>>> ef8a044864c47b290f8a72ac90520ad9578ee1d7
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
