"""init

Revision ID: 0
Revises:
Create Date: 2025-05-01 19:27:13.187381

"""

# revision identifiers, used by Alembic.
revision = "0"
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_process",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Enum("QUEUED", "PROCESSING", "READY", name="imageprocessing"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Дата обновления записи"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_image_process_task_id"), "image_process", ["task_id"], unique=False)
    op.create_table(
        "presigned_url",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Дата создания записи"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Дата обновления записи"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presigned_url")
    op.drop_index(op.f("ix_image_process_task_id"), table_name="image_process")
    op.drop_table("image_process")
    op.execute("DROP TYPE IF EXISTS imageprocessing CASCADE")
    # ### end Alembic commands ###
